spring:
 profiles:
   active:
   - dev
---   
server:
    port: 8001   

mybatis:
  config-localtion: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/*.xml

spring:
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password: root
    dbcp2:
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instace-id: dept-8001.com
    prefer-ip-address: true
---  
server:
    port: 8002   

mybatis:
  config-localtion: classpath:mybatis/mybatis.cfg.xml
  type-aliases-package: com.cloud.entities
  mapper-locations:
  - classpath:mybatis/mapper/*.xml

spring:
  application:
    name: cloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud2
    username: root
    password: root
    dbcp2:
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/
  instance:
    instace-id: dept-8001.com
    prefer-ip-address: true
